# Generated by Django 3.2.3 on 2021-06-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoLast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_2', models.CharField(max_length=255)),
                ('sobrenome_2', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
